### ISSUE TITLE
Not returning all values uploaded into a list

### ISSUE THREAD

**Issue by CyberCrimeConsultant** [jube-home/jube#2]
Hello,

I uploaded the enclosed file with 659 records. 

Unfortunately I can only see the first 18 records in the grid and have no way to see the other records (see screen shot enclosed)

When I query the DB I can see the records are there (see enclosed)

```
select "EntityAnalysisModelListId", count(*), "Deleted"  from "EntityAnalysisModelListValue"  
where "Deleted" is null
group by  "EntityAnalysisModelListId",  "Deleted"
```

Can you consider adding:
- A button to allow a user to progress to see more records / edit them
- A counter stating how many records there are in total

Thank you for your consideration.
[malicious user agents.txt](https://github.com/jube-home/jube/files/9961419/malicious.user.agents.txt)
![List display not showing all records](https://user-images.githubusercontent.com/117478478/200574570-0b93928b-5e20-498a-9ae3-bd49e542ef60.GIF)
![list db query showing records](https://user-images.githubusercontent.com/117478478/200574832-810578eb-5f1a-407b-a162-03649502e48f.GIF)

**Comment by richard-churchman** [comment]
Thank you for raising the ticket. What you describe would seem like a bug. I have looked at the code and can see that paging is in place for this grid (20 on each page),  but it does not seem to be available to move on from what you describe. I have allocated the ticket to myself and will give it attention.

**Comment by CyberCrimeConsultant** [comment]
Thank you, inspecting you can see the data is there on fetch.

See enclosed.

![fetch xhr list records present showing values](https://user-images.githubusercontent.com/117478478/200578237-b4df963a-dd2b-4724-a238-c0fab4072886.GIF)
![fetch xhr list records present showing values 1](https://user-images.githubusercontent.com/117478478
![fetch xhr list records present](https://user-images.githubusercontent.com/117478478/200578267-08ae3e7f-2016-422a-9a2a-02a397adec2f.GIF)
/200578243-86ba8d1c-103c-47be-bb82-c0321337db7c.GIF)

**Comment by richard-churchman** [comment]
Good news. It means there is no bug in the controller, and it will only need a minor update to the Javascript to set up the paging in the grid. Thanks.

**Comment by richard-churchman** [comment]
The Kendo ListView control is being used to present the values.  This control had been used a lot but it was nearly always problematic, so it was mostly written out.  The List and Dictionary pages are the last remaining uses and need to be replaced by a better control (either a Kendo Grid or a similar approach as seen on the Models page).  The replacement of the Kendo ListView control has been added to the product backlog.  In the meantime, all paging has been removed from the current implementations of Kendo ListView which gives a more satisfactory user experience.  All values reliably return and allow for the use of browser native find \ search.
